### ISSUE TITLE
prompt when confirm flag is and quality is not provided

### ISSUE THREAD

**Issue by Amir-m-a** [CodeWithEmad/apyrat#2]
if quality is not provided prompt is always used, which is not desirable when batch downloading and only best quality is desired:
https://github.com/CodeWithEmad/apyrat/blob/50409df64ee87706832adbe459f283a60d7b6638/apyrat/cli.py#L82-L89

something like this would be better imo:
```python
if not quality:
    if confirm:
        return downloader.default_quality()
    else:
        ...
```

**Comment by CodeWithEmad** [comment]
Nice catch!
Would you like to open a PR?
