### ISSUE TITLE
problem with quality selecting

### ISSUE THREAD

**Issue by AliM1988** [CodeWithEmad/apyrat#3]
* Apyrat version:
* Python version:
* Operating System:

### Description

Describe what you were trying to get done.
Tell us what happened, what went wrong, and what you expected to happen.

### What I Did

Example: https://www.aparat.com/playlist/192192

If user selects quality=480p, the videos that have maximum quality < 480p, won't be dowanloaded.

also, parameter -y doesn't work. apyrat -q "480p" -y url , cant download the videos have maximum "360p" quality.

**Comment by CodeWithEmad** [comment]
Thank you for your time. would you like to open a PR?

**Comment by CodeWithEmad** [comment]
The `confirm` issue was fixed in #5 
about the other issue it's fixed and now you can use `apyrat https://www.aparat.com/playlist/192192 -q 400p -y` and it looks for the closest quality.
